[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
poe = "4FomhFzS5vFyUeinAGR865NGm5gntyuNGZHmx8xrfXn5"

[programs.localnet]
poe = "4FomhFzS5vFyUeinAGR865NGm5gntyuNGZHmx8xrfXn5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
