[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
poe = "5CigbaCZ9AALzEebqx5AnckhqUvmgT5fUctmmdGiaXDP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
