import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "@/components/nav-bar";
import Providers from "./providers";
import { SidebarNav } from "@/components/sidebar-nav";
import { SettingsSidebar } from "@/components/settings-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sidebarNavItems = [
  {
    title: "My Polls",
    href: "/settings",
  },
  {
    title: "Create Polls",
    href: "/settings/appearance",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Theme>
            <NavBar />
            <div className="flex flex-col space-y-8 md:flex-row md:space-x-12 md:space-y-0">
              <aside className="hidden md:block md:w-fit border-r">
                <SidebarNav items={sidebarNavItems} />
              </aside>
              <div className="">{children}</div>
            </div>
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
